## Numpy

In [31]:
import numpy as np

In [2]:
a=np.array(43)
print(a)

43


In [3]:
type(a)

numpy.ndarray

In [4]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(a.shape)

(3, 3)


In [8]:
a.ndim

2

In [11]:
b=np.array([
            [[1,2,3],[4,5,6]],
            [[7,8,9],[5,6,8]]
            ])

In [12]:
print(b,b.ndim,b.shape)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [5 6 8]]] 3 (2, 2, 3)


In [13]:
print(b.shape)

(2, 2, 3)


In [16]:
zarray=np.zeroes(6)
print(zarray)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [18]:
oarr=np.ones(10)
print(oarr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print(np.full((4,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [21]:
emp=np.empty((3,2))
print(emp)

[[1.0609979e-313 1.0609979e-313]
 [1.0609979e-313 1.0609979e-313]
 [1.0609979e-313 1.0609979e-313]]


In [23]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [24]:
eye=np.eye(5,5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
# linespace(start,end,no. of point)

print(np.linspace(1,2,5))

[1.   1.25 1.5  1.75 2.  ]


In [28]:
print(np.linspace(1,10,10))
print(np.linspace(1,10,20))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [29]:
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [30]:
arr=np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
arr.dtype

dtype('int32')

In [33]:
newarr=np.array(list(range(10)), dtype=np.float64)
print(newarr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [36]:
# astype()
newarr1=arr.astype(np.float64)
print(newarr1)
print(newarr1.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


## Psuedo Random Number Generation

In [37]:
from numpy import random

In [38]:
np.random.rand(4)

array([0.26632408, 0.4023332 , 0.74192431, 0.22924786])

In [39]:
print(np.random.randn(2,3))

[[-0.29398627  2.51425749 -0.4367171 ]
 [ 0.37965296  1.02739975  0.84890221]]


In [40]:
np.random.normal(size=(4,4))

array([[-0.23894868, -0.55954749,  0.39760908,  0.10258886],
       [-1.88203904,  1.37176649,  1.16404087,  0.06215572],
       [ 1.67461328,  1.36493238,  0.55674371,  1.2415787 ],
       [-1.09496635,  0.31995454,  0.47185173,  0.43754545]])

In [41]:
from numpy.random import *

In [43]:
randn(20)

array([ 0.82475888,  0.5556251 ,  1.21654138,  2.20712916, -2.08051934,
        1.25189445,  0.21497291,  0.62838955, -0.1157037 ,  0.27139166,
       -0.78512713, -0.34839094, -2.80222431, -0.67057618,  0.1255373 ,
        0.94497693, -0.15342103, -0.39455813, -0.63551939, -0.34679848])

In [45]:
randn(20).reshape(5,4)  #reshape(a,b)-> It is used to create a matrix of aXb

array([[ 2.80539665,  0.75893734, -0.3652366 , -0.73319209],
       [-0.14019114, -0.06194244, -0.07085976, -1.60763724],
       [-0.58111513, -2.32722581, -0.45416148,  1.02496136],
       [-0.67212338, -0.12654773,  2.67606586, -0.52966727],
       [-0.2445263 , -0.18662817, -0.52216237,  0.18391747]])

In [48]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
randint(100,200,size=(3,2))

array([[163, 197],
       [152, 144],
       [129, 119]])

In [50]:
arr1=np.array(np.arange(30))
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [52]:
arr1[-1]

29

In [53]:
b = arr1[1:25:2]
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


## Iterate Numpy Arrays

In [55]:
arr=np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
for rows in arr:
    for cell in rows:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [57]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
for cell in arr.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [60]:
# nditer
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### C-order -> row wise
### Fortran order -> column wise

In [62]:
print(np.nditer(arr, order="C"))

In [63]:
for i in np.nditer(arr, order="C"): #row wise
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [64]:
for i in np.nditer(arr, order="F"): #column wise
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


## Boolean Indexing

In [66]:
arr=randint(0,20,15)
print(arr)

[ 6  3  1  4 13 16  4  9 14  3 19  3  1  8  9]


In [67]:
mask=(arr%2==0)
extract_arr = arr[mask]
print(extract_arr)

[ 6  4 16  4 14  8]


In [77]:
days=np.array(['sun','mon','tue','wed','thu','fri','sat','sun','thu',"thu"])
print(days)

['sun' 'mon' 'tue' 'wed' 'thu' 'fri' 'sat' 'sun' 'thu' 'thu']


In [90]:
data=np.random.randn(10,4)
data

array([[ 0.48594293, -1.5506236 , -0.56987488,  0.35893482],
       [-0.15842786,  0.49791074, -1.84749017,  0.68319675],
       [-1.36928461,  0.34398154,  0.63469451, -2.08021604],
       [ 0.02695178, -0.08310252, -0.53926194, -0.07583796],
       [ 0.06776826, -1.17391334, -0.2003114 , -1.51610831],
       [-0.69828698, -0.6296583 ,  0.19032342, -1.13699885],
       [ 1.72172764, -1.35077215,  1.5783691 ,  0.18590749],
       [ 1.14314938,  0.54413123, -1.92678606, -0.92176518],
       [ 0.75589684, -1.32214893, -0.17675268, -0.03165476],
       [-0.76714947,  0.62216299, -0.91956058, -0.41778516]])

In [91]:
data[days=="sun"]

array([[ 0.48594293, -1.5506236 , -0.56987488,  0.35893482],
       [ 1.14314938,  0.54413123, -1.92678606, -0.92176518]])

In [92]:
data[days=="sun",2:]

array([[-0.56987488,  0.35893482],
       [-1.92678606, -0.92176518]])

In [93]:
# ['sun' 'mon' 'tue' 'wed' 'thu' 'fri' 'sat' 'sun' 'thu' 'thu']
con=((days=='sun') | (days=='thu'))
con

array([ True, False, False, False,  True, False, False,  True,  True,
        True])

In [94]:
data[con]

array([[ 0.48594293, -1.5506236 , -0.56987488,  0.35893482],
       [ 0.06776826, -1.17391334, -0.2003114 , -1.51610831],
       [ 1.14314938,  0.54413123, -1.92678606, -0.92176518],
       [ 0.75589684, -1.32214893, -0.17675268, -0.03165476],
       [-0.76714947,  0.62216299, -0.91956058, -0.41778516]])

In [95]:
data[data<0]=1
print(data)

[[0.48594293 1.         1.         0.35893482]
 [1.         0.49791074 1.         0.68319675]
 [1.         0.34398154 0.63469451 1.        ]
 [0.02695178 1.         1.         1.        ]
 [0.06776826 1.         1.         1.        ]
 [1.         1.         0.19032342 1.        ]
 [1.72172764 1.         1.5783691  0.18590749]
 [1.14314938 0.54413123 1.         1.        ]
 [0.75589684 1.         1.         1.        ]
 [1.         0.62216299 1.         1.        ]]


## Stacking

In [99]:
ar1=np.arange(6).reshape(3,2)
print(ar1)

[[0 1]
 [2 3]
 [4 5]]


In [100]:
ar2=np.arange(6,12).reshape(3,2)
print(ar2)

[[ 6  7]
 [ 8  9]
 [10 11]]


In [101]:
# vstack-> vertical (Ek k niche ek)

np.vstack((ar1, ar2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [102]:
# hstack-> horizontal (side by side)

np.hstack((ar1, ar2))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

## Splitting

In [103]:
arr=np.arange(30).reshape(2,15)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [104]:
print(np.hsplit(arr,3))

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [105]:
arr2=np.arange(30).reshape(15,2)
arr2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [106]:
np.vsplit(arr2,3)

[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]),
 array([[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]])]